// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFNyCP7mIoAh5XONKk7BapsMes1DDqTiY',
    appId: '1:430455547992:web:34982ab9a0cb901361c22d',
    messagingSenderId: '430455547992',
    projectId: 'my-study-life-5932b',
    authDomain: 'my-study-life-5932b.firebaseapp.com',
    databaseURL: 'https://my-study-life-5932b.firebaseio.com',
    storageBucket: 'my-study-life-5932b.appspot.com',
    measurementId: 'G-DJB2EXP6E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN93aKwMb7MqK8UKAvQOZLd3_EaSwi5Vg',
    appId: '1:430455547992:android:49fd67365f8d6d03',
    messagingSenderId: '430455547992',
    projectId: 'my-study-life-5932b',
    databaseURL: 'https://my-study-life-5932b.firebaseio.com',
    storageBucket: 'my-study-life-5932b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQXIuz4rRur3LSfKRqtb5oL_egR4c7kY',
    appId: '1:430455547992:ios:c5af102f9a6c97a061c22d',
    messagingSenderId: '430455547992',
    projectId: 'my-study-life-5932b',
    databaseURL: 'https://my-study-life-5932b.firebaseio.com',
    storageBucket: 'my-study-life-5932b.appspot.com',
    iosClientId: '430455547992-digdehufftknf27cie9obdh12vacduok.apps.googleusercontent.com',
    iosBundleId: 'com.mystudylife.app',
  );
}
